/* Generated by Yosys 0.31+16 (git sha1 b04d0e09e, aarch64-apple-darwin20.2-clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* \amaranth.hierarchy  = "top" *)
(* top =  1  *)
(* generator = "Amaranth" *)
module top(out, clk, rst, in);
  reg \$auto$verilog_backend.cc:2097:dump_module$4  = 0;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [40:0] \$1 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [39:0] \$100 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$102 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$103 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$105 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$106 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$108 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$109 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$11 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$111 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$112 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [40:0] \$114 ;
  wire [18:0] \$116 ;
  wire [18:0] \$117 ;
  wire [18:0] \$118 ;
  wire [18:0] \$119 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$12 ;
  wire [18:0] \$120 ;
  wire [18:0] \$121 ;
  wire [18:0] \$122 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:195" *)
  wire \$123 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [42:0] \$126 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$127 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [38:0] \$129 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [39:0] \$131 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$133 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$134 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$136 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$137 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$139 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$14 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$140 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$142 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$143 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [40:0] \$145 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$147 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$148 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$15 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$150 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$151 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$153 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$154 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$156 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$157 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$159 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$160 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [41:0] \$162 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$164 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$165 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$167 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$168 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$17 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$170 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$171 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$173 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$174 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$176 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$177 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$179 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$18 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$180 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [42:0] \$182 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [42:0] \$184 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$185 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [38:0] \$187 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [39:0] \$189 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$191 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$192 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$194 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$195 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$197 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$198 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$2 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [40:0] \$20 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$200 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$201 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [40:0] \$203 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$205 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$206 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$208 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$209 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$211 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$212 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$214 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$215 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$217 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$218 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [40:0] \$22 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [41:0] \$220 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$222 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$223 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$225 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$226 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$228 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$229 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$23 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$231 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$232 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$234 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$235 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$237 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$238 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [42:0] \$240 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [42:0] \$242 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$243 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [38:0] \$245 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [39:0] \$247 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$249 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [38:0] \$25 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$250 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$252 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$253 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$255 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$256 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$258 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$259 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [40:0] \$261 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$263 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$264 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$266 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$267 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$269 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [39:0] \$27 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$270 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$272 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$273 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$275 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$276 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [41:0] \$278 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$280 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$281 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$283 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$284 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$286 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$287 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$289 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$29 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$290 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$292 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$293 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$295 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$296 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [42:0] \$298 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$30 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:135" *)
  wire [18:0] \$300 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$301 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [38:0] \$303 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [39:0] \$305 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$307 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$308 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$310 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$311 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$313 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$314 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$316 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$317 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [40:0] \$319 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$32 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$321 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$322 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$324 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$325 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$327 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$328 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$33 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$330 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$331 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$333 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$334 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [41:0] \$336 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$338 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$339 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$341 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$342 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$344 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$345 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$347 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$348 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$35 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$350 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$351 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$353 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$354 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [42:0] \$356 ;
  wire [18:0] \$358 ;
  wire [18:0] \$359 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$36 ;
  wire [18:0] \$360 ;
  wire [18:0] \$361 ;
  wire [18:0] \$362 ;
  wire [18:0] \$363 ;
  wire [18:0] \$364 ;
  wire [18:0] \$365 ;
  wire [18:0] \$366 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:187" *)
  wire \$367 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:133" *)
  wire [18:0] \$370 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$371 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [38:0] \$373 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [39:0] \$375 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$377 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$378 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$38 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$380 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$381 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$383 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$384 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$386 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$387 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [40:0] \$389 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$39 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$391 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$392 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$394 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$395 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$397 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$398 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [38:0] \$4 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$400 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$401 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$403 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$404 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [41:0] \$406 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$408 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$409 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [40:0] \$41 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$411 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$412 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$414 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$415 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$417 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$418 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$420 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$421 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$423 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$424 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [42:0] \$426 ;
  wire [18:0] \$428 ;
  wire [18:0] \$429 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [40:0] \$43 ;
  wire [18:0] \$430 ;
  wire [18:0] \$431 ;
  wire [18:0] \$432 ;
  wire [18:0] \$433 ;
  wire [18:0] \$434 ;
  wire [18:0] \$435 ;
  wire [18:0] \$436 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:195" *)
  wire \$437 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$44 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [41:0] \$440 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$441 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [38:0] \$443 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [39:0] \$445 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$447 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$448 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$450 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$451 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$453 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$454 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$456 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$457 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [40:0] \$459 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [38:0] \$46 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$461 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$462 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$464 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$465 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$467 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$468 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$470 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$471 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$473 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$474 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [41:0] \$476 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [41:0] \$478 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$479 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [39:0] \$48 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [38:0] \$481 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [39:0] \$483 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$485 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$486 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$488 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$489 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$491 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$492 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$494 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$495 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [40:0] \$497 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$499 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$50 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$500 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$502 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$503 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$505 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$506 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$508 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$509 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$51 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$511 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$512 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [41:0] \$514 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [41:0] \$516 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$517 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [38:0] \$519 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [39:0] \$521 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$523 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$524 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$526 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$527 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$529 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$53 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$530 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$532 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$533 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [40:0] \$535 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$537 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$538 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$54 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$540 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$541 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$543 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$544 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$546 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$547 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$549 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$550 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [41:0] \$552 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:135" *)
  wire [18:0] \$554 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$555 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [38:0] \$557 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [39:0] \$559 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$56 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$561 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$562 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$564 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$565 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$567 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$568 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$57 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$570 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$571 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [40:0] \$573 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$575 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$576 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$578 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$579 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$581 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$582 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$584 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$585 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$587 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$588 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$59 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [41:0] \$590 ;
  wire [18:0] \$592 ;
  wire [18:0] \$593 ;
  wire [18:0] \$594 ;
  wire [18:0] \$595 ;
  wire [18:0] \$596 ;
  wire [18:0] \$597 ;
  wire [18:0] \$598 ;
  wire [18:0] \$599 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [39:0] \$6 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$60 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:187" *)
  wire \$600 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:133" *)
  wire [18:0] \$603 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$604 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [38:0] \$606 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [39:0] \$608 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$610 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$611 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$613 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$614 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$616 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$617 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$619 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [40:0] \$62 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$620 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [40:0] \$622 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$624 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$625 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$627 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$628 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$630 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$631 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$633 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$634 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$636 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$637 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [41:0] \$639 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:135" *)
  wire [18:0] \$64 ;
  wire [18:0] \$641 ;
  wire [18:0] \$642 ;
  wire [18:0] \$643 ;
  wire [18:0] \$644 ;
  wire [18:0] \$645 ;
  wire [18:0] \$646 ;
  wire [18:0] \$647 ;
  wire [18:0] \$648 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:195" *)
  wire \$649 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$65 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [38:0] \$652 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [19:0] \$653 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [19:0] \$654 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [19:0] \$656 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [19:0] \$657 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [19:0] \$659 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [19:0] \$660 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$662 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [38:0] \$664 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [38:0] \$666 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [19:0] \$667 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [19:0] \$668 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [38:0] \$67 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [19:0] \$670 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [19:0] \$671 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [19:0] \$673 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [19:0] \$674 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$676 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [38:0] \$678 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [38:0] \$680 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [19:0] \$681 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [19:0] \$682 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [19:0] \$684 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [19:0] \$685 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [19:0] \$687 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [19:0] \$688 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [39:0] \$69 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$690 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [38:0] \$692 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:135" *)
  wire [18:0] \$694 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [19:0] \$695 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [19:0] \$696 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [19:0] \$698 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [19:0] \$699 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [19:0] \$701 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [19:0] \$702 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$704 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [38:0] \$706 ;
  wire [18:0] \$708 ;
  wire [18:0] \$709 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$71 ;
  wire [18:0] \$710 ;
  wire [18:0] \$711 ;
  wire [18:0] \$712 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:187" *)
  wire \$713 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:133" *)
  wire [18:0] \$716 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [19:0] \$717 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [19:0] \$718 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$72 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [19:0] \$720 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [19:0] \$721 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [19:0] \$723 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [19:0] \$724 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$726 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [38:0] \$728 ;
  wire [18:0] \$730 ;
  wire [18:0] \$731 ;
  wire [18:0] \$732 ;
  wire [18:0] \$733 ;
  wire [18:0] \$734 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:195" *)
  wire \$735 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:187" *)
  wire \$738 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$74 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:187" *)
  wire \$740 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$75 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$77 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$78 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$8 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$80 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$81 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [40:0] \$83 ;
  wire [18:0] \$85 ;
  wire [18:0] \$86 ;
  wire [18:0] \$87 ;
  wire [18:0] \$88 ;
  wire [18:0] \$89 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$9 ;
  wire [18:0] \$90 ;
  wire [18:0] \$91 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:187" *)
  wire \$92 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:133" *)
  wire [18:0] \$95 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *)
  wire [37:0] \$96 ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *)
  wire [38:0] \$98 ;
  (* src = "/Users/anuejn/micromamba/lib/python3.10/site-packages/amaranth/hdl/ir.py:527" *)
  input clk;
  wire clk;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/noiseshaper_cifb.py:67" *)
  input [15:0] in;
  wire [15:0] in;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/noiseshaper_cifb.py:34" *)
  wire [18:0] input_internal_fmt;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/noiseshaper_cifb.py:27" *)
  output out;
  reg out;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/noiseshaper_cifb.py:37" *)
  reg [18:0] quantized_value;
  (* src = "/Users/anuejn/micromamba/lib/python3.10/site-packages/amaranth/hdl/ir.py:527" *)
  input rst;
  wire rst;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/noiseshaper_cifb.py:38" *)
  reg [18:0] stage_0 = 19'h00000;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/noiseshaper_cifb.py:38" *)
  reg [18:0] \stage_0$next ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/noiseshaper_cifb.py:38" *)
  reg [18:0] stage_1 = 19'h00000;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/noiseshaper_cifb.py:38" *)
  reg [18:0] \stage_1$next ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/noiseshaper_cifb.py:38" *)
  reg [18:0] stage_2 = 19'h00000;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/noiseshaper_cifb.py:38" *)
  reg [18:0] \stage_2$next ;
  (* src = "/Users/anuejn/Developer/nAmp/gateware/noiseshaper_cifb.py:38" *)
  wire [18:0] stage_3;
  assign \$9  = $signed(quantized_value) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h6f06c);
  assign \$100  = $signed(\$98 ) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed({ stage_0[18], stage_0[18], stage_0[18], stage_0, 17'h00000 });
  assign \$103  = $signed(quantized_value) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h6f06c);
  assign \$106  = $signed(quantized_value) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h6f06c);
  assign \$109  = $signed(quantized_value) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h6f06c);
  assign \$112  = $signed(quantized_value) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h6f06c);
  assign \$114  = $signed(\$100 ) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed({ \$108 [37], \$111 [37], \$105 [37:34], \$102 [33:0] });
  assign \$123  = $signed(\$114 ) < (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:195" *) $signed(41'h1f800000000);
  assign \$95  = \$123  ? (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:133" *) 19'h40000 : \$64 ;
  assign \$127  = $signed(input_internal_fmt) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h0e17c);
  assign \$12  = $signed(quantized_value) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h6f06c);
  assign \$129  = $signed(\$127 ) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed(38'h0000000000);
  assign \$131  = $signed(\$129 ) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed({ stage_1[18], stage_1[18], stage_1[18], stage_1, 17'h00000 });
  assign \$134  = $signed(quantized_value) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h71e84);
  assign \$137  = $signed(quantized_value) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h71e84);
  assign \$140  = $signed(quantized_value) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h71e84);
  assign \$143  = $signed(quantized_value) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h71e84);
  assign \$145  = $signed(\$131 ) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed({ \$139 [37], \$142 [37], \$136 [37:34], \$133 [33:0] });
  assign \$148  = $signed(stage_0) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h040ed);
  assign \$151  = $signed(stage_0) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h040ed);
  assign \$154  = $signed(stage_0) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h040ed);
  assign \$157  = $signed(stage_0) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h040ed);
  assign \$15  = $signed(quantized_value) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h6f06c);
  assign \$160  = $signed(stage_0) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h040ed);
  assign \$162  = $signed(\$145 ) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed({ \$153 [37], \$156 [37], \$159 [37], \$150 [37:34], \$147 [33:0] });
  assign \$165  = $signed(stage_2) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h7ffc9);
  assign \$168  = $signed(stage_2) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h7ffc9);
  assign \$171  = $signed(stage_2) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h7ffc9);
  assign \$174  = $signed(stage_2) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h7ffc9);
  assign \$177  = $signed(stage_2) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h7ffc9);
  assign \$180  = $signed(stage_2) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h7ffc9);
  assign \$182  = $signed(\$162 ) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed({ \$170 [37], \$173 [37], \$176 [37], \$179 [37], \$167 [37:34], \$164 [33:0] });
  assign \$185  = $signed(input_internal_fmt) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h0e17c);
  assign \$187  = $signed(\$185 ) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed(38'h0000000000);
  assign \$18  = $signed(quantized_value) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h6f06c);
  assign \$189  = $signed(\$187 ) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed({ stage_1[18], stage_1[18], stage_1[18], stage_1, 17'h00000 });
  assign \$192  = $signed(quantized_value) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h71e84);
  assign \$195  = $signed(quantized_value) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h71e84);
  assign \$198  = $signed(quantized_value) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h71e84);
  assign \$201  = $signed(quantized_value) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h71e84);
  assign \$203  = $signed(\$189 ) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed({ \$197 [37], \$200 [37], \$194 [37:34], \$191 [33:0] });
  assign \$206  = $signed(stage_0) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h040ed);
  assign \$20  = $signed(\$6 ) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed({ \$14 [37], \$17 [37], \$11 [37:34], \$8 [33:0] });
  assign \$209  = $signed(stage_0) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h040ed);
  assign \$212  = $signed(stage_0) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h040ed);
  assign \$215  = $signed(stage_0) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h040ed);
  assign \$218  = $signed(stage_0) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h040ed);
  assign \$220  = $signed(\$203 ) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed({ \$211 [37], \$214 [37], \$217 [37], \$208 [37:34], \$205 [33:0] });
  assign \$223  = $signed(stage_2) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h7ffc9);
  assign \$226  = $signed(stage_2) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h7ffc9);
  assign \$229  = $signed(stage_2) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h7ffc9);
  assign \$232  = $signed(stage_2) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h7ffc9);
  assign \$235  = $signed(stage_2) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h7ffc9);
  assign \$238  = $signed(stage_2) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h7ffc9);
  assign \$23  = $signed(input_internal_fmt) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h10f94);
  assign \$240  = $signed(\$220 ) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed({ \$228 [37], \$231 [37], \$234 [37], \$237 [37], \$225 [37:34], \$222 [33:0] });
  assign \$243  = $signed(input_internal_fmt) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h0e17c);
  assign \$245  = $signed(\$243 ) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed(38'h0000000000);
  assign \$247  = $signed(\$245 ) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed({ stage_1[18], stage_1[18], stage_1[18], stage_1, 17'h00000 });
  assign \$250  = $signed(quantized_value) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h71e84);
  assign \$253  = $signed(quantized_value) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h71e84);
  assign \$256  = $signed(quantized_value) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h71e84);
  assign \$25  = $signed(\$23 ) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed(38'h0000000000);
  assign \$259  = $signed(quantized_value) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h71e84);
  assign \$261  = $signed(\$247 ) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed({ \$255 [37], \$258 [37], \$252 [37:34], \$249 [33:0] });
  assign \$264  = $signed(stage_0) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h040ed);
  assign \$267  = $signed(stage_0) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h040ed);
  assign \$270  = $signed(stage_0) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h040ed);
  assign \$273  = $signed(stage_0) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h040ed);
  assign \$276  = $signed(stage_0) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h040ed);
  assign \$278  = $signed(\$261 ) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed({ \$269 [37], \$272 [37], \$275 [37], \$266 [37:34], \$263 [33:0] });
  assign \$27  = $signed(\$25 ) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed({ stage_0[18], stage_0[18], stage_0[18], stage_0, 17'h00000 });
  assign \$281  = $signed(stage_2) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h7ffc9);
  assign \$284  = $signed(stage_2) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h7ffc9);
  assign \$287  = $signed(stage_2) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h7ffc9);
  assign \$290  = $signed(stage_2) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h7ffc9);
  assign \$293  = $signed(stage_2) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h7ffc9);
  assign \$296  = $signed(stage_2) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h7ffc9);
  assign \$298  = $signed(\$278 ) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed({ \$286 [37], \$289 [37], \$292 [37], \$295 [37], \$283 [37:34], \$280 [33:0] });
  assign \$2  = $signed(input_internal_fmt) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h10f94);
  assign \$301  = $signed(input_internal_fmt) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h0e17c);
  assign \$303  = $signed(\$301 ) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed(38'h0000000000);
  assign \$305  = $signed(\$303 ) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed({ stage_1[18], stage_1[18], stage_1[18], stage_1, 17'h00000 });
  assign \$308  = $signed(quantized_value) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h71e84);
  assign \$30  = $signed(quantized_value) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h6f06c);
  assign \$311  = $signed(quantized_value) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h71e84);
  assign \$314  = $signed(quantized_value) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h71e84);
  assign \$317  = $signed(quantized_value) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h71e84);
  assign \$319  = $signed(\$305 ) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed({ \$313 [37], \$316 [37], \$310 [37:34], \$307 [33:0] });
  assign \$322  = $signed(stage_0) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h040ed);
  assign \$325  = $signed(stage_0) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h040ed);
  assign \$328  = $signed(stage_0) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h040ed);
  assign \$331  = $signed(stage_0) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h040ed);
  assign \$334  = $signed(stage_0) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h040ed);
  assign \$336  = $signed(\$319 ) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed({ \$327 [37], \$330 [37], \$333 [37], \$324 [37:34], \$321 [33:0] });
  assign \$33  = $signed(quantized_value) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h6f06c);
  assign \$339  = $signed(stage_2) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h7ffc9);
  assign \$342  = $signed(stage_2) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h7ffc9);
  assign \$345  = $signed(stage_2) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h7ffc9);
  assign \$348  = $signed(stage_2) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h7ffc9);
  assign \$351  = $signed(stage_2) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h7ffc9);
  assign \$354  = $signed(stage_2) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h7ffc9);
  assign \$356  = $signed(\$336 ) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed({ \$344 [37], \$347 [37], \$350 [37], \$353 [37], \$341 [37:34], \$338 [33:0] });
  assign \$367  = $signed(\$356 ) > (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:187" *) $signed(43'h007fffe0000);
  assign \$300  = \$367  ? (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:135" *) 19'h3ffff : { \$242 [42], \$184 [34], \$126 [33:17] };
  assign \$36  = $signed(quantized_value) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h6f06c);
  assign \$371  = $signed(input_internal_fmt) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h0e17c);
  assign \$373  = $signed(\$371 ) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed(38'h0000000000);
  assign \$375  = $signed(\$373 ) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed({ stage_1[18], stage_1[18], stage_1[18], stage_1, 17'h00000 });
  assign \$378  = $signed(quantized_value) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h71e84);
  assign \$381  = $signed(quantized_value) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h71e84);
  assign \$384  = $signed(quantized_value) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h71e84);
  assign \$387  = $signed(quantized_value) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h71e84);
  assign \$389  = $signed(\$375 ) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed({ \$383 [37], \$386 [37], \$380 [37:34], \$377 [33:0] });
  assign \$392  = $signed(stage_0) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h040ed);
  assign \$395  = $signed(stage_0) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h040ed);
  assign \$398  = $signed(stage_0) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h040ed);
  assign \$39  = $signed(quantized_value) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h6f06c);
  assign \$401  = $signed(stage_0) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h040ed);
  assign \$404  = $signed(stage_0) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h040ed);
  assign \$406  = $signed(\$389 ) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed({ \$397 [37], \$400 [37], \$403 [37], \$394 [37:34], \$391 [33:0] });
  assign \$409  = $signed(stage_2) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h7ffc9);
  assign \$412  = $signed(stage_2) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h7ffc9);
  assign \$415  = $signed(stage_2) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h7ffc9);
  assign \$418  = $signed(stage_2) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h7ffc9);
  assign \$41  = $signed(\$27 ) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed({ \$35 [37], \$38 [37], \$32 [37:34], \$29 [33:0] });
  assign \$421  = $signed(stage_2) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h7ffc9);
  assign \$424  = $signed(stage_2) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h7ffc9);
  assign \$426  = $signed(\$406 ) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed({ \$414 [37], \$417 [37], \$420 [37], \$423 [37], \$411 [37:34], \$408 [33:0] });
  assign \$437  = $signed(\$426 ) < (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:195" *) $signed(43'h7f800000000);
  assign \$370  = \$437  ? (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:133" *) 19'h40000 : \$300 ;
  assign \$441  = $signed(input_internal_fmt) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h0dbd0);
  assign \$443  = $signed(\$441 ) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed(38'h0000000000);
  assign \$445  = $signed(\$443 ) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed({ stage_2[18], stage_2[18], stage_2[18], stage_2, 17'h00000 });
  assign \$448  = $signed(quantized_value) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h72430);
  assign \$44  = $signed(input_internal_fmt) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h10f94);
  assign \$451  = $signed(quantized_value) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h72430);
  assign \$454  = $signed(quantized_value) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h72430);
  assign \$457  = $signed(quantized_value) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h72430);
  assign \$459  = $signed(\$445 ) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed({ \$453 [37], \$456 [37], \$450 [37:34], \$447 [33:0] });
  assign \$462  = $signed(stage_1) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h0b3c0);
  assign \$465  = $signed(stage_1) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h0b3c0);
  assign \$468  = $signed(stage_1) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h0b3c0);
  assign \$46  = $signed(\$44 ) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed(38'h0000000000);
  assign \$471  = $signed(stage_1) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h0b3c0);
  assign \$474  = $signed(stage_1) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h0b3c0);
  assign \$476  = $signed(\$459 ) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed({ \$467 [37], \$470 [37], \$473 [37], \$464 [37:34], \$461 [33:0] });
  assign \$479  = $signed(input_internal_fmt) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h0dbd0);
  assign \$481  = $signed(\$479 ) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed(38'h0000000000);
  assign \$483  = $signed(\$481 ) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed({ stage_2[18], stage_2[18], stage_2[18], stage_2, 17'h00000 });
  assign \$486  = $signed(quantized_value) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h72430);
  assign \$48  = $signed(\$46 ) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed({ stage_0[18], stage_0[18], stage_0[18], stage_0, 17'h00000 });
  assign \$489  = $signed(quantized_value) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h72430);
  assign \$492  = $signed(quantized_value) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h72430);
  assign \$495  = $signed(quantized_value) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h72430);
  assign \$497  = $signed(\$483 ) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed({ \$491 [37], \$494 [37], \$488 [37:34], \$485 [33:0] });
  assign \$4  = $signed(\$2 ) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed(38'h0000000000);
  assign \$500  = $signed(stage_1) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h0b3c0);
  assign \$503  = $signed(stage_1) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h0b3c0);
  assign \$506  = $signed(stage_1) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h0b3c0);
  assign \$509  = $signed(stage_1) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h0b3c0);
  assign \$512  = $signed(stage_1) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h0b3c0);
  assign \$514  = $signed(\$497 ) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed({ \$505 [37], \$508 [37], \$511 [37], \$502 [37:34], \$499 [33:0] });
  assign \$517  = $signed(input_internal_fmt) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h0dbd0);
  assign \$51  = $signed(quantized_value) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h6f06c);
  assign \$519  = $signed(\$517 ) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed(38'h0000000000);
  assign \$521  = $signed(\$519 ) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed({ stage_2[18], stage_2[18], stage_2[18], stage_2, 17'h00000 });
  assign \$524  = $signed(quantized_value) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h72430);
  assign \$527  = $signed(quantized_value) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h72430);
  assign \$530  = $signed(quantized_value) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h72430);
  assign \$533  = $signed(quantized_value) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h72430);
  assign \$535  = $signed(\$521 ) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed({ \$529 [37], \$532 [37], \$526 [37:34], \$523 [33:0] });
  assign \$538  = $signed(stage_1) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h0b3c0);
  assign \$541  = $signed(stage_1) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h0b3c0);
  assign \$544  = $signed(stage_1) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h0b3c0);
  assign \$547  = $signed(stage_1) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h0b3c0);
  assign \$54  = $signed(quantized_value) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h6f06c);
  assign \$550  = $signed(stage_1) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h0b3c0);
  assign \$552  = $signed(\$535 ) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed({ \$543 [37], \$546 [37], \$549 [37], \$540 [37:34], \$537 [33:0] });
  assign \$555  = $signed(input_internal_fmt) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h0dbd0);
  assign \$557  = $signed(\$555 ) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed(38'h0000000000);
  assign \$559  = $signed(\$557 ) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed({ stage_2[18], stage_2[18], stage_2[18], stage_2, 17'h00000 });
  assign \$562  = $signed(quantized_value) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h72430);
  assign \$565  = $signed(quantized_value) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h72430);
  assign \$568  = $signed(quantized_value) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h72430);
  assign \$571  = $signed(quantized_value) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h72430);
  assign \$573  = $signed(\$559 ) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed({ \$567 [37], \$570 [37], \$564 [37:34], \$561 [33:0] });
  assign \$576  = $signed(stage_1) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h0b3c0);
  assign \$57  = $signed(quantized_value) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h6f06c);
  assign \$579  = $signed(stage_1) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h0b3c0);
  assign \$582  = $signed(stage_1) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h0b3c0);
  assign \$585  = $signed(stage_1) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h0b3c0);
  assign \$588  = $signed(stage_1) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h0b3c0);
  assign \$590  = $signed(\$573 ) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed({ \$581 [37], \$584 [37], \$587 [37], \$578 [37:34], \$575 [33:0] });
  assign \$600  = $signed(\$590 ) > (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:187" *) $signed(42'h007fffe0000);
  assign \$554  = \$600  ? (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:135" *) 19'h3ffff : { \$516 [41], \$478 [34], \$440 [33:17] };
  assign \$604  = $signed(input_internal_fmt) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h0dbd0);
  assign \$606  = $signed(\$604 ) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed(38'h0000000000);
  assign \$608  = $signed(\$606 ) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed({ stage_2[18], stage_2[18], stage_2[18], stage_2, 17'h00000 });
  assign \$60  = $signed(quantized_value) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h6f06c);
  assign \$611  = $signed(quantized_value) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h72430);
  assign \$614  = $signed(quantized_value) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h72430);
  assign \$617  = $signed(quantized_value) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h72430);
  assign \$620  = $signed(quantized_value) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h72430);
  assign \$622  = $signed(\$608 ) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed({ \$616 [37], \$619 [37], \$613 [37:34], \$610 [33:0] });
  assign \$625  = $signed(stage_1) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h0b3c0);
  assign \$628  = $signed(stage_1) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h0b3c0);
  assign \$62  = $signed(\$48 ) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed({ \$56 [37], \$59 [37], \$53 [37:34], \$50 [33:0] });
  assign \$631  = $signed(stage_1) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h0b3c0);
  assign \$634  = $signed(stage_1) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h0b3c0);
  assign \$637  = $signed(stage_1) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h0b3c0);
  assign \$639  = $signed(\$622 ) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed({ \$630 [37], \$633 [37], \$636 [37], \$627 [37:34], \$624 [33:0] });
  assign \$649  = $signed(\$639 ) < (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:195" *) $signed(42'h3f800000000);
  assign \$603  = \$649  ? (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:133" *) 19'h40000 : \$554 ;
  assign \$654  = $signed(input_internal_fmt) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed(19'h00000);
  assign \$657  = $signed(input_internal_fmt) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed(19'h00000);
  assign \$65  = $signed(input_internal_fmt) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h10f94);
  assign \$660  = $signed(input_internal_fmt) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed(19'h00000);
  assign \$662  = $signed(stage_2) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h3b9d6);
  assign \$664  = $signed({ \$659 [19], \$656 [19:17], \$653 [16:0], 17'h00000 }) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed(\$662 );
  assign \$668  = $signed(input_internal_fmt) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed(19'h00000);
  assign \$671  = $signed(input_internal_fmt) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed(19'h00000);
  assign \$674  = $signed(input_internal_fmt) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed(19'h00000);
  assign \$676  = $signed(stage_2) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h3b9d6);
  assign \$678  = $signed({ \$673 [19], \$670 [19:17], \$667 [16:0], 17'h00000 }) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed(\$676 );
  assign \$67  = $signed(\$65 ) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed(38'h0000000000);
  assign \$682  = $signed(input_internal_fmt) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed(19'h00000);
  assign \$685  = $signed(input_internal_fmt) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed(19'h00000);
  assign \$688  = $signed(input_internal_fmt) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed(19'h00000);
  assign \$690  = $signed(stage_2) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h3b9d6);
  assign \$692  = $signed({ \$687 [19], \$684 [19:17], \$681 [16:0], 17'h00000 }) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed(\$690 );
  assign \$696  = $signed(input_internal_fmt) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed(19'h00000);
  assign \$6  = $signed(\$4 ) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed({ stage_0[18], stage_0[18], stage_0[18], stage_0, 17'h00000 });
  assign \$69  = $signed(\$67 ) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed({ stage_0[18], stage_0[18], stage_0[18], stage_0, 17'h00000 });
  assign \$699  = $signed(input_internal_fmt) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed(19'h00000);
  assign \$702  = $signed(input_internal_fmt) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed(19'h00000);
  assign \$704  = $signed(stage_2) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h3b9d6);
  assign \$706  = $signed({ \$701 [19], \$698 [19:17], \$695 [16:0], 17'h00000 }) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed(\$704 );
  assign \$713  = $signed(\$706 ) > (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:187" *) $signed(39'h07fffe0000);
  assign \$694  = \$713  ? (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:135" *) 19'h3ffff : { \$680 [38], \$666 [34], \$652 [33:17] };
  assign \$718  = $signed(input_internal_fmt) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed(19'h00000);
  assign \$721  = $signed(input_internal_fmt) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed(19'h00000);
  assign \$724  = $signed(input_internal_fmt) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed(19'h00000);
  assign \$726  = $signed(stage_2) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h3b9d6);
  assign \$728  = $signed({ \$723 [19], \$720 [19:17], \$717 [16:0], 17'h00000 }) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed(\$726 );
  assign \$72  = $signed(quantized_value) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h6f06c);
  assign \$735  = $signed(\$728 ) < (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:195" *) $signed(39'h7800000000);
  assign \$716  = \$735  ? (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:133" *) 19'h40000 : \$694 ;
  assign \$738  = $signed(stage_3) > (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:187" *) $signed(19'h00000);
  assign \$740  = $signed(stage_3) > (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:187" *) $signed(19'h00000);
  assign \$75  = $signed(quantized_value) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h6f06c);
  assign \$78  = $signed(quantized_value) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h6f06c);
  assign \$81  = $signed(quantized_value) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h6f06c);
  assign \$83  = $signed(\$69 ) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed({ \$77 [37], \$80 [37], \$74 [37:34], \$71 [33:0] });
  assign \$92  = $signed(\$83 ) > (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:187" *) $signed(41'h007fffe0000);
  assign \$64  = \$92  ? (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:135" *) 19'h3ffff : { \$43 [40], \$22 [34], \$1 [33:17] };
  assign \$96  = $signed(input_internal_fmt) * (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:182" *) $signed(19'h10f94);
  assign \$98  = $signed(\$96 ) + (* src = "/Users/anuejn/Developer/nAmp/gateware/fixed_point.py:157" *) $signed(38'h0000000000);
  always @(posedge clk)
    stage_2 <= \stage_2$next ;
  always @(posedge clk)
    stage_1 <= \stage_1$next ;
  always @(posedge clk)
    stage_0 <= \stage_0$next ;
  always @* begin
    if (\$auto$verilog_backend.cc:2097:dump_module$4 ) begin end
    \stage_0$next  = \$95 ;
    (* src = "/Users/anuejn/micromamba/lib/python3.10/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \stage_0$next  = 19'h00000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2097:dump_module$4 ) begin end
    \stage_1$next  = \$370 ;
    (* src = "/Users/anuejn/micromamba/lib/python3.10/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \stage_1$next  = 19'h00000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2097:dump_module$4 ) begin end
    \stage_2$next  = \$603 ;
    (* src = "/Users/anuejn/micromamba/lib/python3.10/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \stage_2$next  = 19'h00000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2097:dump_module$4 ) begin end
    quantized_value = 19'h60000;
    (* src = "/Users/anuejn/Developer/nAmp/gateware/noiseshaper_cifb.py:58" *)
    casez (\$738 )
      /* src = "/Users/anuejn/Developer/nAmp/gateware/noiseshaper_cifb.py:58" */
      1'h1:
          quantized_value = 19'h20000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2097:dump_module$4 ) begin end
    out = 1'h0;
    (* src = "/Users/anuejn/Developer/nAmp/gateware/noiseshaper_cifb.py:58" *)
    casez (\$740 )
      /* src = "/Users/anuejn/Developer/nAmp/gateware/noiseshaper_cifb.py:58" */
      1'h1:
          out = 1'h1;
    endcase
  end
  assign \$8  = \$9 ;
  assign \$11  = \$12 ;
  assign \$14  = \$15 ;
  assign \$17  = \$18 ;
  assign \$1  = \$20 ;
  assign \$29  = \$30 ;
  assign \$32  = \$33 ;
  assign \$35  = \$36 ;
  assign \$38  = \$39 ;
  assign \$22  = \$41 ;
  assign \$50  = \$51 ;
  assign \$53  = \$54 ;
  assign \$56  = \$57 ;
  assign \$59  = \$60 ;
  assign \$43  = \$62 ;
  assign \$71  = \$72 ;
  assign \$74  = \$75 ;
  assign \$77  = \$78 ;
  assign \$80  = \$81 ;
  assign \$85  = 19'h3ffff;
  assign \$86  = 19'h3ffff;
  assign \$87  = 19'h3ffff;
  assign \$88  = 19'h3ffff;
  assign \$89  = 19'h3ffff;
  assign \$90  = 19'h3ffff;
  assign \$91  = 19'h3ffff;
  assign \$102  = \$103 ;
  assign \$105  = \$106 ;
  assign \$108  = \$109 ;
  assign \$111  = \$112 ;
  assign \$116  = 19'h40000;
  assign \$117  = 19'h40000;
  assign \$118  = 19'h40000;
  assign \$119  = 19'h40000;
  assign \$120  = 19'h40000;
  assign \$121  = 19'h40000;
  assign \$122  = 19'h40000;
  assign \$133  = \$134 ;
  assign \$136  = \$137 ;
  assign \$139  = \$140 ;
  assign \$142  = \$143 ;
  assign \$147  = \$148 ;
  assign \$150  = \$151 ;
  assign \$153  = \$154 ;
  assign \$156  = \$157 ;
  assign \$159  = \$160 ;
  assign \$164  = \$165 ;
  assign \$167  = \$168 ;
  assign \$170  = \$171 ;
  assign \$173  = \$174 ;
  assign \$176  = \$177 ;
  assign \$179  = \$180 ;
  assign \$126  = \$182 ;
  assign \$191  = \$192 ;
  assign \$194  = \$195 ;
  assign \$197  = \$198 ;
  assign \$200  = \$201 ;
  assign \$205  = \$206 ;
  assign \$208  = \$209 ;
  assign \$211  = \$212 ;
  assign \$214  = \$215 ;
  assign \$217  = \$218 ;
  assign \$222  = \$223 ;
  assign \$225  = \$226 ;
  assign \$228  = \$229 ;
  assign \$231  = \$232 ;
  assign \$234  = \$235 ;
  assign \$237  = \$238 ;
  assign \$184  = \$240 ;
  assign \$249  = \$250 ;
  assign \$252  = \$253 ;
  assign \$255  = \$256 ;
  assign \$258  = \$259 ;
  assign \$263  = \$264 ;
  assign \$266  = \$267 ;
  assign \$269  = \$270 ;
  assign \$272  = \$273 ;
  assign \$275  = \$276 ;
  assign \$280  = \$281 ;
  assign \$283  = \$284 ;
  assign \$286  = \$287 ;
  assign \$289  = \$290 ;
  assign \$292  = \$293 ;
  assign \$295  = \$296 ;
  assign \$242  = \$298 ;
  assign \$307  = \$308 ;
  assign \$310  = \$311 ;
  assign \$313  = \$314 ;
  assign \$316  = \$317 ;
  assign \$321  = \$322 ;
  assign \$324  = \$325 ;
  assign \$327  = \$328 ;
  assign \$330  = \$331 ;
  assign \$333  = \$334 ;
  assign \$338  = \$339 ;
  assign \$341  = \$342 ;
  assign \$344  = \$345 ;
  assign \$347  = \$348 ;
  assign \$350  = \$351 ;
  assign \$353  = \$354 ;
  assign \$358  = 19'h3ffff;
  assign \$359  = 19'h3ffff;
  assign \$360  = 19'h3ffff;
  assign \$361  = 19'h3ffff;
  assign \$362  = 19'h3ffff;
  assign \$363  = 19'h3ffff;
  assign \$364  = 19'h3ffff;
  assign \$365  = 19'h3ffff;
  assign \$366  = 19'h3ffff;
  assign \$377  = \$378 ;
  assign \$380  = \$381 ;
  assign \$383  = \$384 ;
  assign \$386  = \$387 ;
  assign \$391  = \$392 ;
  assign \$394  = \$395 ;
  assign \$397  = \$398 ;
  assign \$400  = \$401 ;
  assign \$403  = \$404 ;
  assign \$408  = \$409 ;
  assign \$411  = \$412 ;
  assign \$414  = \$415 ;
  assign \$417  = \$418 ;
  assign \$420  = \$421 ;
  assign \$423  = \$424 ;
  assign \$428  = 19'h40000;
  assign \$429  = 19'h40000;
  assign \$430  = 19'h40000;
  assign \$431  = 19'h40000;
  assign \$432  = 19'h40000;
  assign \$433  = 19'h40000;
  assign \$434  = 19'h40000;
  assign \$435  = 19'h40000;
  assign \$436  = 19'h40000;
  assign \$447  = \$448 ;
  assign \$450  = \$451 ;
  assign \$453  = \$454 ;
  assign \$456  = \$457 ;
  assign \$461  = \$462 ;
  assign \$464  = \$465 ;
  assign \$467  = \$468 ;
  assign \$470  = \$471 ;
  assign \$473  = \$474 ;
  assign \$440  = \$476 ;
  assign \$485  = \$486 ;
  assign \$488  = \$489 ;
  assign \$491  = \$492 ;
  assign \$494  = \$495 ;
  assign \$499  = \$500 ;
  assign \$502  = \$503 ;
  assign \$505  = \$506 ;
  assign \$508  = \$509 ;
  assign \$511  = \$512 ;
  assign \$478  = \$514 ;
  assign \$523  = \$524 ;
  assign \$526  = \$527 ;
  assign \$529  = \$530 ;
  assign \$532  = \$533 ;
  assign \$537  = \$538 ;
  assign \$540  = \$541 ;
  assign \$543  = \$544 ;
  assign \$546  = \$547 ;
  assign \$549  = \$550 ;
  assign \$516  = \$552 ;
  assign \$561  = \$562 ;
  assign \$564  = \$565 ;
  assign \$567  = \$568 ;
  assign \$570  = \$571 ;
  assign \$575  = \$576 ;
  assign \$578  = \$579 ;
  assign \$581  = \$582 ;
  assign \$584  = \$585 ;
  assign \$587  = \$588 ;
  assign \$592  = 19'h3ffff;
  assign \$593  = 19'h3ffff;
  assign \$594  = 19'h3ffff;
  assign \$595  = 19'h3ffff;
  assign \$596  = 19'h3ffff;
  assign \$597  = 19'h3ffff;
  assign \$598  = 19'h3ffff;
  assign \$599  = 19'h3ffff;
  assign \$610  = \$611 ;
  assign \$613  = \$614 ;
  assign \$616  = \$617 ;
  assign \$619  = \$620 ;
  assign \$624  = \$625 ;
  assign \$627  = \$628 ;
  assign \$630  = \$631 ;
  assign \$633  = \$634 ;
  assign \$636  = \$637 ;
  assign \$641  = 19'h40000;
  assign \$642  = 19'h40000;
  assign \$643  = 19'h40000;
  assign \$644  = 19'h40000;
  assign \$645  = 19'h40000;
  assign \$646  = 19'h40000;
  assign \$647  = 19'h40000;
  assign \$648  = 19'h40000;
  assign \$653  = \$654 ;
  assign \$656  = \$657 ;
  assign \$659  = \$660 ;
  assign \$652  = \$664 ;
  assign \$667  = \$668 ;
  assign \$670  = \$671 ;
  assign \$673  = \$674 ;
  assign \$666  = \$678 ;
  assign \$681  = \$682 ;
  assign \$684  = \$685 ;
  assign \$687  = \$688 ;
  assign \$680  = \$692 ;
  assign \$695  = \$696 ;
  assign \$698  = \$699 ;
  assign \$701  = \$702 ;
  assign \$708  = 19'h3ffff;
  assign \$709  = 19'h3ffff;
  assign \$710  = 19'h3ffff;
  assign \$711  = 19'h3ffff;
  assign \$712  = 19'h3ffff;
  assign \$717  = \$718 ;
  assign \$720  = \$721 ;
  assign \$723  = \$724 ;
  assign \$730  = 19'h40000;
  assign \$731  = 19'h40000;
  assign \$732  = 19'h40000;
  assign \$733  = 19'h40000;
  assign \$734  = 19'h40000;
  assign stage_3 = \$716 ;
  assign input_internal_fmt = { in[15], in, 2'h0 };
endmodule
